export const LOAD_USERS_START = 'LOAD_USERS_START';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_FAIL = 'LOAD_USERS_FAIL';

export const LOAD_CANDIDATE_ANSWERS_START = 'LOAD_CANDIDATE_ANSWERS_START';
export const LOAD_CANDIDATE_ANSWERS_SUCCESS = 'LOAD_CANDIDATE_ANSWERS_SUCCESS';
export const LOAD_CANDIDATE_ANSWERS_FAIL = 'LOAD_CANDIDATE_ANSWERS_FAIL';

export const LOAD_VOTER_ANSWERS_START = 'LOAD_VOTER_ANSWERS_START';
export const LOAD_VOTER_ANSWERS_SUCCESS = 'LOAD_VOTER_ANSWERS_SUCCESS';
export const LOAD_VOTER_ANSWERS_FAIL = 'LOAD_VOTER_ANSWERS_FAIL';